### ISSUE TITLE
Error installing in a venv with pip==10.0.0b2

### ISSUE THREAD

**Issue by Ramel** [hforge/itools#100]
As installing master branch, with a Pip version 10.0.0b2 installed and it return at first an error with "pip.download"

Then if I do:
```
pip install -U pip==9.0.3
```
```
Collecting pip==9.0.3
  Using cached pip-9.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.0b2
    Uninstalling pip-10.0.0b2:
      Successfully uninstalled pip-10.0.0b2
Successfully installed pip-9.0.3
```
Then itools can be installed successfully.

**Comment by staverne** [comment]
I've mad a patch for that:

   https://github.com/hforge/itools/commit/b48e3abbc1a21de841ab5d067428746ff02561cf

Now ikaaro master is only compatible with PIP version 10, so please upgrade:

 $ ./bin/pip install --upgrade pip

I'll see if we need to backport that patch in others branch
