### ISSUE TITLE
Fail build when a gulp error occured

### ISSUE THREAD

**Issue by fchenebault** [hforge/itools#48]
Now when a bug on a gulp task occurs, the build continues while it can affect the software running.

It would be very nice to add the possibility to stop the build, with a specific error when a gulp task fails.

**Comment by staverne** [comment]
I've done patch 00c5d7329f474db77bbeb77fb215f95f6667abc2 for that.
Is it enough ?

**Comment by fchenebault** [comment]
Yes I think it's a good start ! Thanks a lot
