### ISSUE TITLE
Modification non visible après un PATCH

### ISSUE THREAD

**Issue by poulp** [hforge/itools#62]
Exemple de vue : 
```python
class MyView(Api_View):

    def PATCH(self, resource, context):
        resource.set_value('toto', 'tata')
        return self.return_json(resource.get_namespace(), context)
```

Si je fait un PATCH sur la vue j’obtiens le namespace de la ressource avant la modification, car le database.save_changes() est fait après avoir construit le namespace de la ressource. Il faudrait pouvoir retourner le namespace de la ressource après le changement.

**Comment by staverne** [comment]
C'était un pb de clear du _brain dans la resource. Fixé via:

https://github.com/hforge/ikaaro/commit/0af9ef663fc5850b4f9066586c80cb0a94677af7
https://github.com/hforge/ikaaro/commit/a424106c1837bfe48462189a3bd7bb6886b67d47

Je clos.
